### ISSUE TITLE
Docs/articles/Lifetimes.md is outdated

### ISSUE THREAD

**Issue by TETYYS** [Barsonax/Singularity#110]

**Comment by Barsonax** [comment]
Thank you for making a issue.

Yup this part is now outdated with the recent changes that changed the lifetime from a enum to a class. This needs to be documented.

Also since its now its a class other ppl can implement their own lifetime which should be noted as well.

Bit busy atm but I can probably fix this soon.

**Comment by Barsonax** [comment]
Updated the outdated info but havent yet added how to implement your own lifetimes
